services:
  guardian-ui:
    image: node:20
    working_dir: /app
    volumes:
      - ./ui:/app
    command: bash -c "npm install && node server.js"
    environment:
      - CLAUDE_API_KEY=
      - GROK_API_KEY=
      - GEMINI_API_KEY=
      - OPENAI_API_KEY=
    ports:
      - "8003:3000"
    restart: always
